### ISSUE TITLE
VeRI Mis-labeled Types

### ISSUE THREAD

**Issue by agude** [JDAI-CV/VeRidataset#1]
The label file for VeRI `train_label.xml` version 1.0 (`<TrainingImages Version="1.0">`) has the following `typeID` errors:

Vehicle 3, 7, and 41 in the training set are labeled as `typeID="0"` which does not correspond to a legal type in `list_type.txt`.

Vehicle 0003 is an Audi Q5, which we believe is `typeID="2"` (SUV).
Vehicle 0007 is a Nissan of some sort. It looks like a cross-over, so again `typeID="2"` (SUV).
Vehicle 0041 is a Hummer H2, which should be `typeID="2"` (SUV).

**Comment by VehicleReId** [comment]
Thanks very much!
We have corrected the errors and updated the train_label.xml which can be downloaded from: 
https://drive.google.com/file/d/0B0o1ZxGs_oVZZVRPZEw2b2hheXc/view?usp=sharing

PS. vehicle 0003 is an Audi Q3.  :)

**Comment by agude** [comment]
Thanks! Maybe you should bump the version to 1.1 to differentiate it from the previous version?

**Comment by irisqp** [comment]
> 
> 
> The label file for VeRI `train_label.xml` version 1.0 (`<TrainingImages Version="1.0">`) has the following `typeID` errors:
> 
> Vehicle 3, 7, and 41 in the training set are labeled as `typeID="0"` which does not correspond to a legal type in `list_type.txt`.
> 
> Vehicle 0003 is an Audi Q5, which we believe is `typeID="2"` (SUV).
> Vehicle 0007 is a Nissan of some sort. It looks like a cross-over, so again `typeID="2"` (SUV).
> Vehicle 0041 is a Hummer H2, which should be `typeID="2"` (SUV).

hi @agude thanks for your notice. I know I'm late, but I want to use this DataSet to train a Deep Sort model, I contanct the original owner of this dataset, but nobody reply me, could you please send me a copy of this data if you still have it?  thank you very much!  here are my email address: irisqp@126.com.

**Comment by agude** [comment]
Hi @irisqp,

I no longer have the data, as I have left the lab where I used to work. I believe I wasn't allowed to distribute it anyway. I'm sorry to hear that the original authors seem to have disappeared!
