### ISSUE TITLE
 ICCV 2019 paper to be added

### ISSUE THREAD

**Issue by zhengthomastang** [JDAI-CV/VeRidataset#10]
We have a newly published ICCV 2019 paper with experiments on VeRi-776. Hope it could be added to the state-of-the-art results and references. 

@inproceedings{Tang19PAMTRI,
author = {Zheng Tang and Milind Naphade and Stan Birchfield and Jonathan Tremblay and William Hodge and Ratnesh Kumar and Shuo Wang and Xiaodong Yang},
title = {{PAMTRI}: {P}ose-aware multi-task learning for vehicle re-identification using highly randomized synthetic data},
booktitle = {Proc. ICCV},
pages = {211--220},
address = {Seoul, Korea},
year = {2019}
}

Link: http://openaccess.thecvf.com/content_ICCV_2019/papers/Tang_PAMTRI_Pose-Aware_Multi-Task_Learning_for_Vehicle_Re-Identification_Using_Highly_Randomized_ICCV_2019_paper.pdf

Our state-of-the-art performance is as follow (presented in Table 2 of the paper): 
mAP: 71.88%
Rank-1: 92.86%
Rank-5: 96.97%

**Comment by taosean** [comment]
Hi @zhengthomastang , I noticed there is another paper claims to achieve state-of-the-art performance on VeRi dataset, they claim to achieve the performance: (in Table III)
mAP: 72.5
Rank-1: 93.3
Rank-5: 97.1
How do you think about this?

The paper is: **Stripe-based and Attribute-aware Network: A Two-Branch Deep Model for Vehicle Re-identification**.

**Comment by zhengthomastang** [comment]
@taosean Thank you for sharing! Their performance is really impressive. It would be great if both our and their papers could be listed among the state-of-the-art on the benchmark.

**Comment by VehicleReId** [comment]
Recent results have been updated. Thanks!
