### ISSUE TITLE
what is the “ours” in the state-of-the-art results.

### ISSUE THREAD

**Issue by canteen-man** [JDAI-CV/VeRidataset#11]
I don’t find any paper or references about the method “ours”.
But the rank1 and rank5 of the method "ours" are really good.
Is there any references of this method？
Thank you.

**Comment by VehicleReId** [comment]
It is just our performance based on a group of tricks and tuning on hyper-parameters.

**Comment by RQuispeC** [comment]
is there a paper for these tricks? and which model did you use?

**Comment by lxc86739795** [comment]
> is there a paper for these tricks? and which model did you use?
Our framework is released here:
https://github.com/JDAI-CV/fast-reid
