### ISSUE TITLE
No reply to email

### ISSUE THREAD

**Issue by Sybilly** [JDAI-CV/VeRidataset#13]
I sent an email and stated my name and organization. The dataset will be not for commercial use, but only for the completion of the experiment. But no reply has been received yet.

**Comment by VehicleReId** [comment]
> I sent an email and stated my name and organization. The dataset will be not for commercial use, but only for the completion of the experiment. But no reply has been received yet.

Sorry for the late reply. Maybe there are some problems of the email system.

**Comment by PHCLenzi** [comment]
@VehicleReId @Sybilly . Sorry for the dumb question, but the email to send the full name and information for the non-commercial project that requires the ReVi dataset is xinchenliu@bupt.cn? I tried contacting through this address, but I was unsuccessful.
