### ISSUE TITLE
how can i email you to get the data set?

### ISSUE THREAD

**Issue by irisqp** [JDAI-CV/VeRidataset#3]
@VehicleReId 
    Thanks for your work!
    My name is QiaoPeng, and I'm a student from Xidian University. I've been working on vehicle detection and track. Recently I'm trying to use deep_sort algorithm to track cars, since the deep_sort is aimed for track of pedestrian. I need to train deep_sort model with cars dataset to improve the performance of deep_sort algorithm. Then I found this dataset, I really need this dataset for my research. I couldn't find your email address, so I write this reply, hopefully you can see it and help me get the dataset. here are my email address irisqp@126.com. looking forward to hear from you soon. Thankyou so much !

**Comment by todofixthis** [comment]
Instructions can be found on <https://vehiclereid.github.io/VeRi/#download>:

> To encourage related research, we will provide the dataset according to your request. Please email your full name and affiliation to the contact person (xinchenliu at bupt dot edu dot cn). We ask for your information only to make sure the dataset is used for non-commercial purposes. We will not give it to any third party or publish it publicly anywhere.

**Comment by PHCLenzi** [comment]
@irisqp , did you use the email: xinchenliu@bupt.edu.cn? Did you have success?
