### ISSUE TITLE
one question

### ISSUE THREAD

**Issue by zhaojc001** [JDAI-CV/VeRidataset#9]
the password of the baidudisk about VeRi,can you tell me?

**Comment by Hackerlil** [comment]
maybe the contact is busy.I have send my request for many days.but I haven't get responce

**Comment by lxc86739795** [comment]
If you still did not receive the response from xinchenliu [at] bupt [dot] edu [dot] cn, please contact liuxinchen1 [at] jd [dot] com. :)
